/**
 * GET /.netlify/functions/instagram
 *
 * Returns the most recent Instagram media for @minibarnmarket as JSON, so the
 * home page can show a feed that keeps itself current instead of six posts
 * somebody has to paste into build.py by hand.
 *
 *   { "posts": [ { id, type, url, thumb, link, caption, when } ], "at": "..." }
 *
 * WHY A FUNCTION AND NOT A SCRIPT TAG
 * Meta retired the free oEmbed endpoint and there is no keyless way to read an
 * account's media any more. The read needs a token, and a token in a static
 * page is a token anybody can copy. So the token stays server-side, in a
 * Netlify environment variable, and the browser only ever sees this JSON.
 *
 * SETUP — once, and none of it happens in a chat window
 *   1. The Instagram account must be a Business or Creator account. Personal
 *      accounts cannot be read by the API at all.
 *   2. developers.facebook.com -> create an app -> add the product
 *      "Instagram" -> "API setup with Instagram login".
 *   3. Generate a long-lived access token for @minibarnmarket with the
 *      instagram_business_basic permission.
 *   4. In Netlify: Site configuration -> Environment variables -> add
 *      IG_TOKEN = that token. Never paste it into a file, a message, or here.
 *   5. Redeploy.
 *
 * Until step 4 is done this returns an empty list and the page quietly falls
 * back to the pinned posts in tools/build.py. Nothing breaks; the feed simply
 * is not live yet.
 *
 * The token expires after 60 days. On a git-connected deploy
 * instagram-refresh.mjs rolls it before then and parks the fresh one in
 * Netlify Blobs, which this reads in preference to the environment variable.
 * On a drag-and-drop deploy there is no npm install, so Blobs is not there and
 * the token has to be regenerated by hand every couple of months. Put a
 * reminder in a calendar, or move this site to a git deploy.
 */
const GRAPH = "https://graph.instagram.com/v23.0";
const FIELDS = "id,caption,media_type,media_url,thumbnail_url,permalink,timestamp";
const LIMIT = 12;

/* The posts pinned in tools/build.py, so the no-token path has something to
   fetch. Keep this list in step with IG_POSTS there. */
const PINNED = [
  ["reel/DbJutd0BsoV", "Better than organic, non-toxic, small batch, handmade."],
  ["reel/DZG45lfvVFX", "Lime, but make it caviar. Australian finger limes, straight off the farm."],
  ["reel/DZGzfBtP9ZN", "Your neighborhood farm stand is open. Always."],
  ["reel/DXSOjBqjnKv", "Sourdough, sweet treats, eggs, produce in season, and a good deal more."],
  ["reel/DZhEprNpUPL", "A San Diego County farm stand that never closes."],
  ["reel/Danv9abBoim", "Twenty-four hours, seven days, held up by the honor system."],
];

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

/* ---------------------------------------------------------------------------
   THE NO-TOKEN PATH

   Every public Instagram post has an embed page, and that page carries the
   still image in its markup. Fetching it from here — a server, with an
   ordinary browser user-agent — costs nothing, needs no Meta app and no
   token, and gives the grid real pictures the day the site goes up.

   It cannot know what is NEW, which is what the token buys. So this is the
   floor, not the ceiling: pictures immediately, latest-posts once IG_TOKEN
   is set.

   Instagram has changed this markup before and will again, which is why
   three different shapes are tried and a miss is simply dropped rather than
   thrown. A tile with no picture falls back to its caption, which is exactly
   what the page does anyway.
--------------------------------------------------------------------------- */
function stillFrom(html) {
  /* The first version of this looked for
         class="EmbeddedMediaImage" ... src="..."
     which is exactly what the page looks like in a browser — and that was the
     mistake. What I read to write it was the DOM *after* Instagram's own
     JavaScript had run. A server gets the raw HTML, where the same picture is
     a JSON-escaped URL buried in a script tag, attribute order is not
     guaranteed, and every slash is written \/.
     Six fetches came back 200, 605KB, no login wall, and matched nothing.

     So this now works the other way round: find any Facebook CDN photo URL in
     the response, in whatever form, and unescape it. Blunt, but it cannot be
     broken by an attribute reordering or a renamed JSON key. */
  const unescape = (u) =>
    u.replace(/\\u0026/g, "&")
     .replace(/\\\//g, "/")
     .replace(/&amp;/g, "&");

  // Ordered by how much we trust them, not by how they are written.
  const probes = [
    /"display_url"\s*:\s*"([^"]+)"/,
    /class="EmbeddedMediaImage"[^>]*\ssrc="([^"]+)"/,
    /<img[^>]+src="([^"]+)"[^>]*class="EmbeddedMediaImage"/,
    /<meta[^>]+property="og:image"[^>]+content="([^"]+)"/,
    // Last resort, and the one most likely to survive a redesign: any fbcdn
    // photo URL at all, backslashes allowed because JSON escapes them.
    /(https:(?:\\?\/){2}[^"'\s]*?fbcdn\.net(?:\\?\/)v(?:\\?\/)t51[^"'\s]*?\.(?:jpg|jpeg|webp)[^"'\s]*)/,
  ];
  for (const re of probes) {
    const m = html.match(re);
    if (m && m[1]) {
      const u = unescape(m[1]);
      if (/^https:\/\//.test(u)) return u;
    }
  }
  return "";
}

/* Turned on with ?peek=<index>. Returns what the fetched page actually looks
   like around anything image-shaped, so the next guess is not a guess. It
   returns no personal data — only markup Instagram serves to anyone. */
function peekAt(html) {
  const marks = ["display_url", "EmbeddedMediaImage", "og:image", "fbcdn.net",
                 "image_versions", "thumbnail_src", "\"src\""];
  const out = {};
  for (const m of marks) {
    const i = html.indexOf(m);
    out[m] = i < 0 ? null : { at: i, around: html.slice(Math.max(0, i - 90), i + 260) };
  }
  out._bytes = html.length;
  out._head = html.slice(0, 200);
  return out;
}

async function pinnedWithStills(trace) {
  const out = await Promise.all(
    PINNED.map(async ([path, caption]) => {
      const note = { post: path };
      try {
        const res = await fetch(`https://www.instagram.com/${path}/embed/captioned/`, {
          headers: { "user-agent": UA, "accept-language": "en-US,en;q=0.9" },
        });
        note.status = res.status;
        if (!res.ok) {
          trace.push(note);
          return null;
        }
        const html = await res.text();
        note.bytes = html.length;
        // A login wall comes back as a 200 with a perfectly ordinary-looking
        // page, so the status code alone proves nothing. This is the tell.
        note.walled = /LoginAndSignupPage|accounts\/login/.test(html);
        const thumb = stillFrom(html);
        note.found = Boolean(thumb);
        trace.push(note);
        if (!thumb) return null;
        return {
          id: path,
          type: path.startsWith("reel/") ? "VIDEO" : "IMAGE",
          thumb,
          link: `https://www.instagram.com/${path}/`,
          caption,
          when: "",
        };
      } catch (err) {
        note.error = String(err && err.message ? err.message : err);
        trace.push(note);
        return null;
      }
    })
  );
  return out.filter(Boolean);
}

async function currentToken() {
  // A refreshed token in Blobs beats the one the environment was seeded with,
  // because the environment variable is never rewritten.
  //
  // The import is dynamic and wrapped on purpose. This site is deployed by
  // dropping a zip on Netlify, which does not run npm install, so
  // @netlify/blobs may simply not be there. A static import would take the
  // whole function down with it; this way the feed still works off IG_TOKEN
  // and only the automatic token roll is missing.
  try {
    const { getStore } = await import("@netlify/blobs");
    const rolled = await getStore("instagram").get("token");
    if (rolled) return rolled.trim();
  } catch (err) {
    /* no Blobs on this deploy — fall through to the environment variable */
  }
  return (process.env.IG_TOKEN || "").trim();
}

function tidy(caption) {
  if (!caption) return "";
  // Captions are written for Instagram: hashtag walls, @ mentions, emoji
  // bullets, "Comment FARMSTAND for the location". None of that reads well
  // in a tile, so take the first real sentence and stop.
  const firstBlock = caption.split("\n").find((l) => l.trim().length > 12) || caption;
  return firstBlock
    .replace(/#[\w]+/g, "")
    .replace(/[✅❤️\u{1F300}-\u{1FAFF}]/gu, "")
    .replace(/\s{2,}/g, " ")
    .trim()
    .slice(0, 120);
}

/* A short browser cache and a longer edge cache. The shelf changes daily, not
   by the second, and this should not hit Instagram once per visitor. */
const CACHE = {
  "Cache-Control": "public, max-age=300",
  "Netlify-CDN-Cache-Control": "public, max-age=1800, stale-while-revalidate=86400",
};

export default async (req) => {
  // Diagnostic. ?peek=0..5 dumps what Instagram actually returned for that
  // pinned post, so a broken extractor can be fixed in one round instead of
  // three. Harmless to leave in — it exposes nothing that is not public.
  try {
    const peek = new URL(req.url).searchParams.get("peek");
    if (peek !== null) {
      const i = Math.max(0, Math.min(PINNED.length - 1, parseInt(peek, 10) || 0));
      const res = await fetch(`https://www.instagram.com/${PINNED[i][0]}/embed/captioned/`, {
        headers: { "user-agent": UA, "accept-language": "en-US,en;q=0.9" },
      });
      const html = await res.text();
      return Response.json(
        { post: PINNED[i][0], status: res.status, found: stillFrom(html), peek: peekAt(html) },
        { headers: { "Cache-Control": "no-store" } }
      );
    }
  } catch (err) { /* fall through to the normal path */ }

  const token = await currentToken();

  /* Every no-token and every failure path comes through here, and every one
     of them carries a trace. Open /instagram.json in a browser and it says
     what it actually did — which beats redeploying and hoping. Nothing in the
     trace is sensitive: status codes, byte counts, and whether a still was
     found. The token is never echoed. */
  const empty = async (reason) => {
    const trace = [];
    const pinned = await pinnedWithStills(trace);
    return Response.json(
      { posts: pinned, source: "pinned", reason, trace },
      { headers: CACHE }
    );
  };

  // No token, so no way to ask what is newest — but the pinned posts can
  // still be given their real pictures. Better than six text cards.
  if (!token) return empty("IG_TOKEN is not set on this site");

  try {
    const res = await fetch(
      `${GRAPH}/me/media?fields=${FIELDS}&limit=${LIMIT}&access_token=${encodeURIComponent(token)}`
    );
    if (!res.ok) return empty(`instagram returned ${res.status}`);

    const body = await res.json();
    const posts = (body.data || [])
      .filter((m) => m.permalink)
      .map((m) => ({
        id: m.id,
        type: m.media_type,
        // A reel's media_url is the video file; thumbnail_url is the still we
        // actually want in a grid.
        thumb: m.thumbnail_url || m.media_url || "",
        link: m.permalink,
        caption: tidy(m.caption),
        when: m.timestamp || "",
      }))
      .filter((m) => m.thumb);

    if (!posts.length) return empty("the account returned no media");

    return Response.json(
      { posts, source: "live", at: new Date().toISOString() },
      { headers: CACHE }
    );
  } catch (err) {
    return empty(String(err && err.message ? err.message : err));
  }
};
