/* Service worker — generated by tools/build.py. Do not edit by hand. */
const VERSION = "4d61fc81af";
const SHELL = "shell-" + VERSION;
const TILES = "tiles-v1";
const MEDIA = "media-v1";

const PRECACHE = [
  "/",
  "/map",
  "/stay",
  "/watch",
  "/more",
  "/install",
  "/css/app.css?v=f6b267d9",
  "/js/app.js?v=f6b267d9",
  "/js/map.js?v=f6b267d9",
  "/manifest.webmanifest",
  "/data/landmarks.json",
  "/data/roads.json",
  "/data/stands.json",
  "/images/logo-fhg.png",
  "/images/logo-fstv.png",
  "/images/logo-mbm.png",
  "/images/mbm-painting.jpg",
  "/images/pin.png",
  "/images/pin@2x.png",
  "/images/ramona-farmstand-map.jpg",
  "/images/rbr-eggs-kids.jpg",
  "/images/stay-mr.jpg",
  "/images/stay-rbr.jpg",
  "/icons/apple-touch-icon.png?v=52c766ca",
  "/icons/icon-192.png?v=52c766ca",
  "/icons/icon-512.png?v=52c766ca",
  "/icons/maskable-512.png?v=52c766ca"
];

/* Cache-first with a ceiling. Map tiles are the reason this app is worth
   installing — Ramona backcountry has real dead zones — but an unbounded tile
   cache will happily eat a gigabyte, so it is trimmed. */
const TILE_CAP = 600;

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(SHELL)
      // addAll is all-or-nothing: one 404 and the whole install fails and the
      // app has no offline support at all. Adding them one at a time means a
      // missing file costs that file, not everything.
      .then((c) => Promise.all(PRECACHE.map((u) => c.add(u).catch(() => {}))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith("shell-") && k !== SHELL).map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

async function trim(cacheName, max) {
  const c = await caches.open(cacheName);
  const keys = await c.keys();
  if (keys.length <= max) return;
  for (const k of keys.slice(0, keys.length - max)) await c.delete(k);
}

/* ---- push ----
   The payload is JSON we send ourselves, but a push service is allowed to
   deliver an empty one, and a `push` event with no notification shown is a
   permission violation in Chrome that eventually revokes the subscription.
   So there is always a fallback. */
self.addEventListener("push", (e) => {
  let d = {};
  try { d = e.data ? e.data.json() : {}; } catch (err) { d = {}; }
  const title = d.title || "Mini Barn Market";
  e.waitUntil(self.registration.showNotification(title, {
    body: d.body || "Something new at the stand.",
    icon: "/icons/icon-192.png?v=52c766ca",
    badge: "/icons/icon-192.png?v=52c766ca",
    image: d.image || undefined,
    // Same tag replaces rather than stacks, so two runs of the watcher can
    // never leave two identical notifications on the lock screen.
    tag: d.tag || "mbm",
    renotify: true,
    data: { url: d.url || "/", link: d.link || "" }
  }));
});

self.addEventListener("notificationclick", (e) => {
  e.notification.close();
  const target = (e.notification.data && e.notification.data.url) || "/";
  e.waitUntil((async () => {
    // Focus the app if it is already open rather than piling up tabs.
    const all = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    for (const c of all) {
      if (c.url.indexOf(self.location.origin) === 0 && "focus" in c) {
        await c.focus();
        if ("navigate" in c) await c.navigate(target);
        return;
      }
    }
    await self.clients.openWindow(target);
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);

  // Never cache the Instagram function. A cached feed that says "today" and
  // is a week old is worse than no feed.
  if (url.pathname.startsWith("/.netlify/")) return;

  // Navigations: network first so a deploy shows up, cache as the fallback so
  // a dead zone does not end the session.
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(SHELL).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((r) => r || caches.match("/")))
    );
    return;
  }

  // Map tiles and Instagram thumbnails: cache first, network to fill.
  const isTile = /tile\.openstreetmap|basemaps\.cartocdn|server\.arcgisonline/.test(url.href);
  const isMedia = /fbcdn\.net|cdninstagram|i\.ytimg\.com/.test(url.href);
  if (isTile || isMedia) {
    const box = isTile ? TILES : MEDIA;
    e.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(box).then((c) => c.put(req, copy).then(() => {
            if (isTile) trim(TILES, TILE_CAP);
          }));
        }
        return res;
      }).catch(() => hit))
    );
    return;
  }

  // Everything else on this origin: cache first, it is all content-hashed or
  // static.
  if (url.origin === self.location.origin) {
    e.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(SHELL).then((c) => c.put(req, copy));
        }
        return res;
      }))
    );
  }
});
